// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eelherngdbozrxggyjcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlbGhlcm5nZGJvenJ4Z2d5amN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MzI0ODEsImV4cCI6MjA2NzAwODQ4MX0.VJaJUPpjGt9wUUgw-xv9-N2iY6UBYz_8X49fvmR938o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});